spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://192.168.0.105:5432/storage_users
    password: srvadmin
    username: srvadmin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
jwt:
  key: "b2aa66f53265c3f235f80becec1b4a585b4b281d50e063badaf54328d1c2e625"
  expiration-time: 3600000
